ALTER TABLE jobs ADD COLUMN IF NOT EXISTS plan_json JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS result_checksum VARCHAR(64);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS resource_budget_json JSONB;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS transferred_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS spilled_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS operator_metrics_json JSONB;
